spring:
 application:
  name: eureka-service
 
server:
 port: 8300

eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
  server:
   waitTimeInMsWhenSyncEmpty: 0
  service-url:
   defaultZone: http://localhost:8300/eureka

zuul:
 prefix: /api
 routes: 
  db-service:
   path: /db-service/**
   url: http://localhost:8305
  stock-service:
   path: /stock-service/**
   url: http://localhost:8301   
